// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/service.go -destination=internal/repository/mocks/mock_repository.go -package=mocks HiTalentRepositoryInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "TestHitalent/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHiTalentRepositoryInterface is a mock of HiTalentRepositoryInterface interface.
type MockHiTalentRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockHiTalentRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockHiTalentRepositoryInterfaceMockRecorder is the mock recorder for MockHiTalentRepositoryInterface.
type MockHiTalentRepositoryInterfaceMockRecorder struct {
	mock *MockHiTalentRepositoryInterface
}

// NewMockHiTalentRepositoryInterface creates a new mock instance.
func NewMockHiTalentRepositoryInterface(ctrl *gomock.Controller) *MockHiTalentRepositoryInterface {
	mock := &MockHiTalentRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockHiTalentRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHiTalentRepositoryInterface) EXPECT() *MockHiTalentRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CreateChat mocks base method.
func (m *MockHiTalentRepositoryInterface) CreateChat(chat *models.Chat) (*models.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChat", chat)
	ret0, _ := ret[0].(*models.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChat indicates an expected call of CreateChat.
func (mr *MockHiTalentRepositoryInterfaceMockRecorder) CreateChat(chat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChat", reflect.TypeOf((*MockHiTalentRepositoryInterface)(nil).CreateChat), chat)
}

// CreateMessage mocks base method.
func (m *MockHiTalentRepositoryInterface) CreateMessage(chatId int, message *models.Message) (*models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMessage", chatId, message)
	ret0, _ := ret[0].(*models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMessage indicates an expected call of CreateMessage.
func (mr *MockHiTalentRepositoryInterfaceMockRecorder) CreateMessage(chatId, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMessage", reflect.TypeOf((*MockHiTalentRepositoryInterface)(nil).CreateMessage), chatId, message)
}

// DeleteChat mocks base method.
func (m *MockHiTalentRepositoryInterface) DeleteChat(chatId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChat", chatId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChat indicates an expected call of DeleteChat.
func (mr *MockHiTalentRepositoryInterfaceMockRecorder) DeleteChat(chatId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChat", reflect.TypeOf((*MockHiTalentRepositoryInterface)(nil).DeleteChat), chatId)
}

// GetChat mocks base method.
func (m *MockHiTalentRepositoryInterface) GetChat(chatId, limit int) (*models.ChatAndMessagesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChat", chatId, limit)
	ret0, _ := ret[0].(*models.ChatAndMessagesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChat indicates an expected call of GetChat.
func (mr *MockHiTalentRepositoryInterfaceMockRecorder) GetChat(chatId, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChat", reflect.TypeOf((*MockHiTalentRepositoryInterface)(nil).GetChat), chatId, limit)
}
