// Code generated by MockGen. DO NOT EDIT.
// Source: internal/transport/server.go
//
// Generated by this command:
//
//	mockgen -source=internal/transport/server.go -destination=internal/service/mocks/mock_service.go -package=mocks HiTalentServiceInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "TestHitalent/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHiTalentServiceInterface is a mock of HiTalentServiceInterface interface.
type MockHiTalentServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockHiTalentServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockHiTalentServiceInterfaceMockRecorder is the mock recorder for MockHiTalentServiceInterface.
type MockHiTalentServiceInterfaceMockRecorder struct {
	mock *MockHiTalentServiceInterface
}

// NewMockHiTalentServiceInterface creates a new mock instance.
func NewMockHiTalentServiceInterface(ctrl *gomock.Controller) *MockHiTalentServiceInterface {
	mock := &MockHiTalentServiceInterface{ctrl: ctrl}
	mock.recorder = &MockHiTalentServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHiTalentServiceInterface) EXPECT() *MockHiTalentServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateChat mocks base method.
func (m *MockHiTalentServiceInterface) CreateChat(chat *models.Chat) (*models.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChat", chat)
	ret0, _ := ret[0].(*models.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChat indicates an expected call of CreateChat.
func (mr *MockHiTalentServiceInterfaceMockRecorder) CreateChat(chat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChat", reflect.TypeOf((*MockHiTalentServiceInterface)(nil).CreateChat), chat)
}

// CreateMessage mocks base method.
func (m *MockHiTalentServiceInterface) CreateMessage(chatId string, message *models.Message) (*models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMessage", chatId, message)
	ret0, _ := ret[0].(*models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMessage indicates an expected call of CreateMessage.
func (mr *MockHiTalentServiceInterfaceMockRecorder) CreateMessage(chatId, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMessage", reflect.TypeOf((*MockHiTalentServiceInterface)(nil).CreateMessage), chatId, message)
}

// DeleteChat mocks base method.
func (m *MockHiTalentServiceInterface) DeleteChat(chatId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChat", chatId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChat indicates an expected call of DeleteChat.
func (mr *MockHiTalentServiceInterfaceMockRecorder) DeleteChat(chatId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChat", reflect.TypeOf((*MockHiTalentServiceInterface)(nil).DeleteChat), chatId)
}

// GetChat mocks base method.
func (m *MockHiTalentServiceInterface) GetChat(chatId string, limit int) (*models.ChatAndMessagesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChat", chatId, limit)
	ret0, _ := ret[0].(*models.ChatAndMessagesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChat indicates an expected call of GetChat.
func (mr *MockHiTalentServiceInterfaceMockRecorder) GetChat(chatId, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChat", reflect.TypeOf((*MockHiTalentServiceInterface)(nil).GetChat), chatId, limit)
}
